name: pass_pens
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- Supabase untuk Auth & Database ---
  supabase_flutter: ^2.10.3

  # --- State Management ---
  provider: ^6.1.2

  # --- Kamera / Galeri ---
  image_picker: ^1.1.1         

  # --- GPS Lokasi ---
  geolocator: ^14.0.2          
  permission_handler: ^11.0.0  

  # --- ML Kit Face Detection ---
  google_mlkit_face_detection: ^0.13.1

  # --- Notifikasi ---
  flutter_local_notifications: ^19.5.0

  # --- Multi Select (Wajib untuk Register Dosen) ---
  multi_select_flutter: ^4.1.3

  # --- Animasi UI (FadeInDown, FadeInUp, dll) ---
  animate_do: ^3.3.4

  # --- Tanggal & Format Date ---
  intl: ^0.19.0   # <= WAJIB, BIAR DateFormat TIDAK ERROR

  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # versi stabil (6.0 menyebabkan warning banyak)
  flutter_lints: ^3.0.1  

flutter:
  uses-material-design: true

  assets:
    - assets/icon_login.png
    - assets/logoPENS.png
    - assets/PASS.png
